name: flutter_messenger
description: "A new Flutter project."


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1



dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter


  image_picker: ^0.8.7+4
  mime: ^1.0.4

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  shared_preferences: ^2.5.3
  web_socket_channel: ^3.0.3
  provider: ^6.1.5
  rename: ^3.1.0
  http_parser: ^4.1.2

  path_provider: ^2.0.15
  permission_handler: ^11.3.1
  dio: ^5.8.0+1
  intl: ^0.20.2
  gal: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0




flutter:
  assets:
    - assets/dark_wallpaper.png
    - assets/white_wallpaper.png

  uses-material-design: true

  generate: true

